kind: pipeline
name: startpage-docker-image
type: docker

clone:
  disable: true

steps:
  - name: git
    image: plugins/git
    settings:
      depth: 10
      skip_verify: true
  - name: debug
    image: busybox
    commands:
      - ls -la
  - name: image
    image: plugins/docker
    settings:
      username: docker
      password: pw4docker
      registry: registry.chickenoncow.com
      repo: registry.chickenoncow.com/gfawcett/startpage
